config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'

  get "admin" => 'admin#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :support_requests, only: %i[ index update ]

  resources :users

  resources :products do
    get :who_bought, on: :member
  end
  
  scope '(:locale)' do
    resources :orders
    resources :line_items
    resources :carts
    root 'store#index', as: 'store_index'
  end
end

app/views/layouts/_cart.html.erb
<% if cart and not cart.line_items.empty? %>
  <div id= "cart" class= "bg-white rounded p-2">
    <%= render cart %>
  </div>
<% else %>
  <div id= "cart"></div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Books Online Store</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header class="bg-yellow-500/25 py-4 px-6 flex items-center justify-between">
      <div class="flex items-center space-x-4">
        <%= image_tag 'my_header_logo.png', class: 'h-16' %>

        <% unless session[:user_id] %>
          <aside data-controller="locale">
            <%= form_tag store_index_path, method: 'get', class: 'locale flex items-center space-x-4' do %>
              <%= select_tag 'set_locale', options_for_select(LANGUAGES, I18n.locale.to_s),
                  onchange: 'this.form.submit()', class: 'px-1 py-1 pr-7 border rounded-lg bg-yellow-500/25 focus:outline-none focus:ring focus:border-blue-500' %>
              <%= submit_tag 'Submit', data: { 'locale-target' => 'submit' }, class: 'px-4 py-2 bg-yellow-500/25 rounded-lg hover:bg-blue-600' %>
            <% end %>
          </aside>
        <% end %>
      </div>

      <h1 class="text-2xl font-semibold"><%= @page_title %></h1>
    </header>

    <section class='flex'>
      <nav class='bg-yellow-500/30 p-6'>
        <%= render partial: 'layouts/cart', locals: {cart: @cart} %>

        <ul class='text-lg font-medium leading-10'>
          <li><a href=''><%= t('.home') %></a></li>
          <li><a href='/questions'><%= t('.questions') %></a></li>
          <li><a href='/news'><%= t('.news') %></a></li>
          <li><a href='/contact'><%= t('.contact') %></a></li>
          <li></li>
        </ul>

        <% if session[:user_id] %>
          <hr class='bg-black my-2 p-0.5 rounded-lg'>

          <ul class='leading-8 font-medium text-lg'>
            <li><%= link_to 'Orders', orders_path %></li>
            <li><%= link_to 'Products', products_path %></li>
            <li><%= link_to 'Users', users_path %></li>
            <li><%= link_to 'Logout', logout_path, data: { turbo_method: :delete } %></li>
          </ul>
        <% end %>
      </nav>
      <main class="container mx-auto mt-4 px-5 flex">
        <%= yield %>
      </main>
    </section>
  </body>
</html>